Add ability to bake BHoMObjects and BHoMGeometry
BHoM/Grasshopper_Toolkit pull request #550
Opened 2020-09-29 13:59 UTC by IsakNaslundBh

### Issues addressed by this PR

Closes #549

- Making it possible to bake out BHoMGeometry
   - One half of this was actually already working. You actually were able to bake BHoMGeometry from a Data parameter. For this, Just needed to make the BHoMGeometry parameter bake aware as well.
- Adding Baking capability to the BHoMObject Goo and paramter

### Test files

### Changelog

### Additional comments

2020-09-30 02:53 UTC, adecler requested changes
Brilliant! Thanks @IsakNaslundBh 😄 

Tested both on output param and param components and it works great for the 3 categories (Geometry, IObject & BHoM Object). 

I have never really used bake myself so probably a good idea for someone else to review as well. Otherwise, looks good to me both on code an functionality side with one minor caveat.

2020-09-30 02:53 UTC, adecler commented on Grasshopper_UI/Components/Parameters/Param_BHoMGeometry.cs
> +                if (item.BakeGeometry(doc, att, out guid))
Probably a good idea to check that `item` is not null

2020-09-30 02:53 UTC, adecler commented on Grasshopper_UI/Components/Parameters/Param_BHoMGeometry.cs
> +                if (item.BakeGeometry(doc, null, out guid))
Probably a good idea to check that `item` is not null

2020-09-30 02:53 UTC, adecler commented on Grasshopper_UI/Components/Parameters/Param_BHoMObject.cs
> +                if (item.BakeGeometry(doc, null, out guid))
Probably a good idea to check that `item` is not null

2020-09-30 02:53 UTC, adecler commented on Grasshopper_UI/Components/Parameters/Param_BHoMObject.cs
> +                if (item.BakeGeometry(doc, att, out guid))
Probably a good idea to check that `item` is not null

2020-09-30 02:53 UTC, adecler commented on Grasshopper_UI/Components/Parameters/Param_IObject.cs
> +                if (item.BakeGeometry(doc, null, out guid))
Probably a good idea to check that `item` is not null

2020-09-30 02:53 UTC, adecler commented on Grasshopper_UI/Components/Parameters/Param_IObject.cs
> +                if (item.BakeGeometry(doc, att, out guid))
Probably a good idea to check that `item` is not null

2020-09-30 06:36 UTC, IsakNaslundBh commented on Grasshopper_UI/Components/Parameters/Param_BHoMGeometry.cs
> +                if (item.BakeGeometry(doc, att, out guid))
the 'true' in `this.VolatileData.AllData(true)` is supposed to take care of this

![image](https://user-images.githubusercontent.com/22005920/94650984-faa18880-02f7-11eb-817d-4d147c813900.png)

but can add an extra null check anyway, just to be extra safe if you think that is worth it? :)

2020-09-30 06:42 UTC, adecler commented on Grasshopper_UI/Components/Parameters/Param_BHoMGeometry.cs
> +                if (item.BakeGeometry(doc, att, out guid))
Ha! Fair enough 😋 

Happy to approve then.

2020-09-30 06:43 UTC, adecler approved these changes

2020-09-30 14:38 UTC, pawelbaran approved these changes
LGTM, works as expected, the only issue I see is the fact that pulled objects need to be cast to `BHoMObject` before they can be baked - this, however, seems to be out of the scope of this PR therefore happy to approve.

2020-10-06 02:39 UTC, adecler commented
/azp run Grasshopper_Toolkit.CheckInstaller

2020-10-06 02:51 UTC, merged