Replace all Param_ScriptVariable with our own solution
BHoM/Grasshopper_Toolkit pull request #557
Opened 2020-10-22 07:23 UTC by adecler

### Issues addressed by this PR

Closes #543

This is required to get access to `CastFrom(object source)` and `CastTo<Q>(ref Q target)` methods.
This will solve the problem of Rhino geometry not being casted back and forth (e.g. `CreateCustom` & `GetProperty` components).

I also had to do a bit of refactoring of the BH parameters as that addition of the variable parameter would have added to already existing code duplication. So now, the `IObject`, `BHoMObject`, and `Variable` parameters are all inheriting from the `Bakeable` parameter. I would have liked to also add the `Geometry` parameter to that list but it was already inheriting from a different class than the others and it was out of the scope of this PR to change that. 

### Test files
- Make sure that those two issues are resolved:
   - #540: `GetProperty` returns unconverted BHoM geometries
   - #529: `CreateCustom` does not convert breps

- In general, test that were relying on variable parameters such as `CreateCustom`, `SetProperty` and `Explode`. 
- Also make sure that old scripts containing those are still working

2020-10-22 11:42 UTC, IsakNaslundBh commented
As discussed with @adecler think it is sensible to keep the goos to object for this PR and resolve it in a separate issue. Issue raised here:

https://github.com/BHoM/Grasshopper_Toolkit/pull/557

Will test this with the expectation that the previous params all work as before, and any param that previously returned script variable not should have the added benefit this PR actually set out to resolve!

2020-10-22 12:28 UTC, IsakNaslundBh requested changes
Some tweaks needed to get baking working. Suggested changes below seem to do it.

2020-10-22 12:28 UTC, IsakNaslundBh commented on Grasshopper_UI/Templates/BakeableParam.cs
> +    public abstract class BakeableParam<T> : BHoMParam<T>, IGH_BakeAwareObject where T : class, IGH_Goo
```suggestion
    public abstract class BakeableParam<T> : BHoMParam<T>, IGH_BakeAwareObject where T : class, IGH_Goo, IGH_BakeAwareData
```

2020-10-22 12:28 UTC, IsakNaslundBh commented on Grasshopper_UI/Templates/BakeableParam.cs
> +            foreach (Engine.Grasshopper.Objects.GH_BakeableObject<T> item in this.VolatileData.AllData(true))
```suggestion
            foreach (T item in this.VolatileData.AllData(true))
```

The T on the param level here is already a Goo, so should be just T, not `....Goo<T>`

It required the additional constraint above as well to work.

Layercake GH.....

2020-10-22 12:28 UTC, IsakNaslundBh commented on Grasshopper_UI/Templates/BakeableParam.cs
> +            foreach (Engine.Grasshopper.Objects.GH_BakeableObject<T> item in this.VolatileData.AllData(true))
```suggestion
            foreach (T item in this.VolatileData.AllData(true))
```

2020-10-22 12:30 UTC, IsakNaslundBh commented on Grasshopper_UI/Templates/BakeableParam.cs
> +            foreach (Engine.Grasshopper.Objects.GH_BakeableObject<T> item in this.VolatileData.AllData(true))
Instead of changing to T could instead had changed to `IGH_BakeAwareData` I think

2020-10-22 12:41 UTC, IsakNaslundBh commented
Another thing found that I am not sure if it is out of scope of the PR or not is that any component placed before this change does not seem to reap the quite massive benefit this PR brings. Not sure if that is out of scope for this PR or not!

Can also add, to not sound all negative, I _LOVE_ this update. Think it will reduce so much of annoying friction we have been experiencing for various things!

2020-10-22 13:33 UTC, IsakNaslundBh commented
Some issues exploding/get proeprty from obejcts with list of list proeprty. Not sure if it is related to this PR (do not think it is) in any shape or form, but:

![image](https://user-images.githubusercontent.com/22005920/96878971-c1ce7c80-147b-11eb-9f6d-2d4ad52a5e1c.png)

Have raised https://github.com/BHoM/Grasshopper_Toolkit/issues/559 for it if better of tackle it separately. Also have a testfile in there.

2020-10-23 02:06 UTC, adecler commented on Grasshopper_UI/Templates/BakeableParam.cs
> +    public abstract class BakeableParam<T> : BHoMParam<T>, IGH_BakeAwareObject where T : class, IGH_Goo
That interface is for the level of the Goo, not the params

2020-10-23 02:08 UTC, adecler commented on Grasshopper_UI/Templates/BakeableParam.cs
> +            foreach (Engine.Grasshopper.Objects.GH_BakeableObject<T> item in this.VolatileData.AllData(true))
> Instead of changing to T could instead had changed to `IGH_BakeAwareData` I think, but can leave it up to you @adecler

Yes, this is more correct as the interface `IGH_Goo` (which is the constraint on `T`) doesn't provide a `BakeGeometry` method

2020-10-23 02:09 UTC, adecler commented on Grasshopper_UI/Templates/BakeableParam.cs
> +            foreach (Engine.Grasshopper.Objects.GH_BakeableObject<T> item in this.VolatileData.AllData(true))
I don't believe this is correct. See comment above

2020-10-23 02:35 UTC, adecler commented
Thanks @IsakNaslundBh ,

I have fixed the baking issue although made a slightly different correction than yours.

As for your other two comments:

>Another thing found that I am not sure if it is out of scope of the PR or not is that any component placed before this change does not seem to reap the quite massive benefit this PR brings. Not sure if that is out of scope for this PR or not!

Yes, I am aware of that but decided it was not worth the risk and the decent amount of work required to make that happen (you basically have to individually replace every script parameter and recreate the connections). The old scripts were working fine without that feature and will still work fine despite the change. That's plenty enough in my book 😄 

>Some issues exploding/get property from objects with list of list property. Not sure if it is related to this PR (do not think it is) in any shape or form

Yes, this is a separate issue that already happens on the master.  Note that getting a lists of lists property works fine if you extract that property from a single object. The error occurs when you have multiple objects in the first input. Will need to investigate further.

![image](https://user-images.githubusercontent.com/16853390/96949834-68b62580-151b-11eb-9c4d-484f1e179000.png)

2020-10-26 08:04 UTC, IsakNaslundBh commented on Grasshopper_UI/Templates/BakeableParam.cs
> +    public abstract class BakeableParam<T> : BHoMParam<T>, IGH_BakeAwareObject where T : class, IGH_Goo
yes, hence putting it on the where part, as in `T: ... , ... ,   IGH_BakeAwareData` :)

2020-10-26 08:43 UTC, IsakNaslundBh commented on Grasshopper_UI/Templates/BakeableParam.cs
> +            foreach (Engine.Grasshopper.Objects.GH_BakeableObject<T> item in this.VolatileData.AllData(true))
Yeah, the the `T` solution would require the additional constraint on the `T` as shown above :)

Think we probably should put that in anyway, as if we want the Param to be bakeable, then the Goo should be as well (whether we use the `T` or the explicit interface solution matters less I think)

2020-10-27 12:49 UTC, IsakNaslundBh requested changes
Found an issue with the casting to valuetypes, in particular, to numbers:

![image](https://user-images.githubusercontent.com/22005920/97303824-35e19980-185b-11eb-80a7-da5529783149.png)


Will need to ensure that the CastTo for the new generic variable is able to be casted to any of the base level types such as integers and doubles when appropriate.

2020-11-03 02:35 UTC, adecler commented
Thanks Isak,

This should now be fixed for all primitives. I have also added support for Guids:

![image](https://user-images.githubusercontent.com/16853390/97944686-3aa8cf00-1dc0-11eb-98b9-5e62184f0300.png)

2020-11-05 08:21 UTC, IsakNaslundBh approved these changes
This seem to be working well for me now. Would not mind a second review as well @al-fisher @pawelbaran @alelom as this is touching a lot of stuff, but approving to unlock @adecler

2020-11-05 08:31 UTC, adecler commented
/azp run Grasshopper_Toolkit.CheckInstaller

2020-11-05 10:57 UTC, alelom submitted a review, later dismissed
Working well for me too.

2020-11-05 11:43 UTC, IsakNaslundBh requested changes
Testing this a bit more, seems like the issue with primitives presists when used as inputs, even though the parameters are working fine:

![image](https://user-images.githubusercontent.com/22005920/98236915-5e0c7f00-1f64-11eb-82a4-24db4ec75531.png)

2020-11-05 14:45 UTC, IsakNaslundBh requested changes
Found another issue now.


Can not covert from the new generic goo to our type goo.

![image](https://user-images.githubusercontent.com/22005920/98255649-ec412f00-1f7d-11eb-9c70-be2a7ac60a67.png)


Think the issue for this is that the casting in the Type goo needs to be expanded:

![image](https://user-images.githubusercontent.com/22005920/98255575-d3387e00-1f7d-11eb-923d-278606b74865.png)

2020-11-06 07:04 UTC, adecler commented
QuickCast ? What now ? 😕 

I was getting a bit tired of this casting system from DR so I creted a separate `Compute` file with castings for all the existing GH_Goo (that had a corresponding `ToGHX` method). That should take care of it. The casting method taking care of the `IGH_QuickCast` ones covers all the possible types I found through reflection so that should now be good too.

![image](https://user-images.githubusercontent.com/16853390/98335920-dc3e5380-2040-11eb-89bf-1f22d273348e.png)

I have also taken care of the error we had on the casting in the `Type` Goo. 

Hopefully that should now be enough to settle that issue for good 🤞

2020-11-08 13:48 UTC, FraserGreenroyd commented
I've removed my request for review because I am heavily out of the loop on this one (apologies) and it appears that @IsakNaslundBh and @alelom are on track with this. Please feel free to re-request if my review is needed, but I feel the others have it in hand :smile:

2020-11-11 07:16 UTC, adecler commented
@IsakNaslundBh , would be able to do another review (hopefully the final one) ? 
This repo is getting pretty crowded with another PR still waiting to be pushed and more issue to fix this sprint.

2020-11-11 08:44 UTC, IsakNaslundBh approved these changes
Found another case not working, but was not working on master either (using addition with vectors):
![image](https://user-images.githubusercontent.com/22005920/98789103-196c6200-2402-11eb-97e9-80a5b6767495.png)

On master it is behaving as the geometry param is (in the explode) which is arguably worse as it does not give any errors, while the new one does, so not enough to hold of this PR.

Given the overly complex casting system of GH, I am not sure if I have missed to check something, but look to me like the core principles are working as expected now at least! Could preform the basic operations with numbers, see geometry and bake straight from the pull etc!

Ready to approve now for further testing by more users in the alphas!

2020-11-11 08:50 UTC, adecler commented
/azp run Grasshopper_Toolkit.CheckInstaller

2020-11-11 08:56 UTC, adecler commented
Thanks @IsakNaslundBh ,  I know where this one is coming from: 

In `PreferredCast`, I treat any `IObject` differently from primitive types since the later don't need baking and other fancy Casting based on what they are plugged into. Sadly Rhino Vectors and Points are structures not classes. So they are treated by GH the same way as primitives (with that parallel messy casting system). There might be a way to keep the best of both world but I am not sure how. So for now, I decided it was a small price to pay. Can you raise that as a separate issue though ? When I can find the courage, I can have another look into it.

2020-11-11 09:05 UTC, merged

2020-11-11 09:09 UTC, IsakNaslundBh commented
Issue already raised here: https://github.com/BHoM/Grasshopper_Toolkit/issues/565 😄