Caching of preview meshes to improve performance
BHoM/Grasshopper_Toolkit pull request #656
Opened 2022-05-09 15:33 UTC by IsakNaslundBh

### Issues addressed by this PR

Closes #655

Changes the way geometry is rendered from rendering Surface geometry via the specific render method accepting Breps, to instead extract PreviewMeshes that are cached at first preview and then reused to preview.

Also storing preview material rather than only preview colour, as creating those for each frame also slows things down.

This will increase the demand on RAM slightly, but from initial testing with a quite significant amount of obejcts this has not yet proven to be a massive problem.

If it is, we could have a look to instead remove the cached BHoM geometry and Rhino geometry, for them to be extracted on the fly instead, and directly turned to the preview meshes.

### Test files

### Changelog

### Additional comments

2022-05-09 17:26 UTC, FraserGreenroyd requested changes
Some minor spelling/formatting changes requested from code review (functionality review not yet performed).

Tagging @alelom as well to take a glance through just to check if this causes any concern for him with the remote compute work he's working on following our nuget discussion this morning @alelom ?

Happy for conversations to be marked resolved if an answer is given @IsakNaslundBh 👍

2022-05-09 17:26 UTC, FraserGreenroyd commented on Grasshopper_UI/Goos/GH_BakeableObject.cs
> +                    m_IsMeshPreviewable = false;    //If no mesh could be extracted, set flag as no required to check again for the same geometry
```suggestion
                    m_IsMeshPreviewable = false;    //If no mesh could be extracted, set flag as not required to check again for the same geometry
```

2022-05-09 17:26 UTC, FraserGreenroyd commented on Grasshopper_UI/Render/CreatePreviewMesh.cs
> +            if (parameters == null)
Or at least a blank line after the brackets if you prefer the use of the brackets, but separation of `if(params == null)` from the rest is good.

2022-05-09 17:26 UTC, FraserGreenroyd commented on Grasshopper_UI/Render/CreatePreviewMesh.cs
> +            RHG.Mesh mesh = new RHG.Mesh();
```suggestion
            if (array == null)
                return new RHG.Mesh();

            if (array.Length == 1)
                return array[0];

            RHG.Mesh mesh = new RHG.Mesh();
```

Again just giving some spacing around the different checks/blocks. Happy to keep the brackets but if so can we then put a blank line between each different `if` block instead.

2022-05-09 17:26 UTC, FraserGreenroyd commented on Grasshopper_UI/Render/RenderMaterial.cs
> +                ghColour.B == pColour.B) // Excluding Alpha channel from comparison
Surely if any of these are `!=` then we don't need to check the others? In which case it's better to use `&&` than `&` I'd imagine?

2022-05-09 17:26 UTC, FraserGreenroyd commented on Grasshopper_UI/Goos/GH_BakeableObject.cs
> +            ResetPreviewMeshes();   //Clears cashed preview meshes and resets preview flag.
Just to check, will this be called any time any geometry of any object being rendered is changed/set? As in, if I have a panel, but then change its geometry, will be render with the changed geometry or will it use the cached geometry?

2022-05-10 07:39 UTC, IsakNaslundBh commented on Grasshopper_UI/Goos/GH_BakeableObject.cs
> +            ResetPreviewMeshes();   //Clears cashed preview meshes and resets preview flag.
That is a good question, but do not think this PR will change from the current behaviour (where we are using cached Rhino geometry to render anyway).

The SetGeometry method is called when the Value of the Goo is set, https://github.com/BHoM/Grasshopper_Toolkit/blob/d3d16e824d779e7e4b6f68f9fb9458f023978fa4/Grasshopper_UI/Goos/GH_BakeableObject.cs#L58-L69

So that case is handled. I guess, theoretically, you could get the reference of a Panel from a particular `GH_BakeableObject` and change it without this method being called again, and hence preview being wrong. I think that never happens in practice though, and if it did I do not think this PR makes it worse.

Worth to keep an eye on for sure, but think it is a separate issue that we can log if you think required.

2022-05-10 07:41 UTC, IsakNaslundBh commented on Grasshopper_UI/Render/CreatePreviewMesh.cs
> +            catch (Exception)
Dont think so. Would prefer for the preview system to give as little errors on components as possible. Also, doubt this will crash that often (if any time at all), but good to have as a safety.

Also, for this, I tried to just follow what had been done in the other files :)

2022-05-10 07:42 UTC, IsakNaslundBh commented on Grasshopper_UI/Render/RenderMaterial.cs
> +                ghColour.B == pColour.B) // Excluding Alpha channel from comparison
fully agree. Just copied the other method and did not really think about it. Will fix, and might fix the other method as well.

2022-05-10 08:25 UTC, FraserGreenroyd commented on Grasshopper_UI/Goos/GH_BakeableObject.cs
> +            ResetPreviewMeshes();   //Clears cashed preview meshes and resets preview flag.
Happy with that answer @IsakNaslundBh - happy for it to not be a separate issue at this stage until we find an issue

2022-05-10 08:25 UTC, FraserGreenroyd commented on Grasshopper_UI/Render/CreatePreviewMesh.cs
> +            catch (Exception)
Understood, sounds good to me 😄

2022-05-12 11:36 UTC, michaelhoehn approved these changes
I've compared the code on main and the PR code against the sample scripts and am very happy with the performance improvements. I didn't notice any adverse side effects on memory usage when upping the panel counts quite significantly. The only real difference was noticed when orbiting/panning around the models which provided a significant framerate performance boost. Happy to see this merged 🐛

2022-05-12 15:10 UTC, FraserGreenroyd approved these changes
Changes are good, happy with the discussion, great work, thanks @IsakNaslundBh 

@alelom unless you desperately need this for your remote computing work, I won't plan to make a nuget out of this until the next beta - but if you do need it desperately then let me know!

2022-05-12 15:12 UTC, IsakNaslundBh commented
@BHoMBot check ready-to-merge

2022-05-13 06:44 UTC, merged